### ISSUE TITLE
Do you have a compiled version hosted on a CDN?

### ISSUE THREAD

**Issue by nishith83** [kommitters/editorjs-toggle-block#101]
I was looking to integrate this plugin into our editor.
However, since we are still using older javascript, I was looking for a a compiled version of the plugin.

Like with other plugins of editorsjs, all of them provide a CDN version for direct usage.

Let me know if this is something which is already available.

**Comment by miguelnietoa** [comment]
Hey @nishith83, You could use this URL:
https://cdn.jsdelivr.net/npm/editorjs-toggle-block@0.2.5/dist/bundle.min.js

This one will be included in the README in the next release! 🚀

**Comment by nishith83** [comment]
Thanks @miguelnietoa
