### ISSUE TITLE
Is there a way to change toggle section placeholder

### ISSUE THREAD

**Issue by Arash1381-y** [kommitters/editorjs-toggle-block#147]
I'm trying to use this feature in my editor but, the contents are not in English. Like other tools, I have tested some config but it doesn't work and the default "toggle" and "Empty toggle ..." remain.

is there any way to change this default text for the toggle?

**Comment by juanhurtado10** [comment]
Hi there 👋!! 

There is no way to change the placeholder at this time. However, it is a necessary improvement. We will let you know once it is implemented.

Best!

**Comment by miguelnietoa** [comment]
Hi @Arash1381-y 😄 
This feature is available at [v0.3.0](https://github.com/kommitters/editorjs-toggle-block/releases/tag/v0.3.0) 🎉 thanks.
