### ISSUE TITLE
Infinite loop with non-editable block inside toggle

### ISSUE THREAD

**Issue by ash14** [kommitters/editorjs-toggle-block#162]
### Precheck

- [x] Do a quick search and make sure the bug has not been reported yet.
- [x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [x] Finally, be nice and have fun!.

### Description

Pressing shift+tab to remove a block from inside a toggle will result in an infinite loop when a non-editable block (e.g. [delimiter](https://github.com/editor-js/delimiter)) is present inside the toggle.

### Environment

* Editor.js version: 2.25.0

### Current behavior

See https://codesandbox.io/s/editorjs-toggle-block-test-case-bz2e4r for reproducible steps.

### Expected behavior

In the above case, we should expect to see the caret moved to the first paragraph with the toggle set to having 2 items.

### Additional context

Seems the offending line is https://github.com/kommitters/editorjs-toggle-block/blob/v0.3.2/src/index.js#L367; there's no check that the index hasn't changed inside the loop.

**Comment by miguelnietoa** [comment]
Fixed in version `0.3.5`. Thanks, @karolrojas07 for contributing! 🚀
