### ISSUE TITLE
Settings popover broken from editor.js v2.26 and up

### ISSUE THREAD

**Issue by somejonus** [kommitters/editorjs-toggle-block#176]
With the update to editor.js v2.26 the settings popover does not open anymore.

**Expected behavior:**

On click of the `ce-toolbar__settings-btn` button the settings popover opens.

**Current behavior:**

On click of the `ce-toolbar__settings-btn` button nothing happens.

**Error in console:**

`editorjs-toggle-block@latest:7 Uncaught TypeError: Cannot read properties of undefined (reading 'lastChild') at I.renderSettings`

Looks like the whole `ce-settings` div in `ce-toolbox` is missing.

**Comment by Thimows** [comment]
Seeing the same thing when using the latest version via jsdelivr 0.3.11

**Comment by miguelnietoa** [comment]
Editorjs v2.26 brought a lot of breaking changes for this plugin (DOM structure was changed), I recommend if possible to keep on editorjs v2.25

**Comment by MarioRodriguezS** [comment]
@somejonus  @Thimows Thanks a lot for reporting the issue, it was solved and the solution is available in v0.3.14. Please let us know if this solution proves helpful to you.
