### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by 4e576rt8uh9ij9okp** [kommitters/editorjs-toggle-block#188]
### Precheck

- [ x] Do a quick search and make sure the bug has not been reported yet.
- [ x] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ x] Finally, be nice and have fun!.

### Description

I'm getting an error that ToggleBlock isn't defined.

### Environment

* Editor.js version: 2.26.5
* Plugins you use with their versions: none
* Device, Browser, OS: PC, Brave, Win10

### Current behavior

It says that ToggleBlock isn't defined, means that there is something wrong with ToggleBlock itself.
I'm using your CDN link.

```
const editor = new EditorJS({
    holder: "editor",
    onReady: () => {
        editor.blocks.renderFromHTML("<h1>Hello there xD</h1>")
    },
    tools: {
        toggle: {
            class: ToggleBlock,
            inlineToolbar: true
        }
    },
    autofocus: true
})
```

### Expected behavior
ToggleBlock should exist when using the CDN link?

### Additional context
-

**Comment by miguelnietoa** [comment]
Hey @4e576rt8uh9ij9okp we just released version `0.3.9` which includes a fix for this issue!! 

You could use this CDN link specifying the version:
```
https://cdn.jsdelivr.net/npm/editorjs-toggle-block@0.3.9
```

Thanks for letting us know 💯
