### ISSUE TITLE
Copy / paste toggles share the same foreign key and should be unique, so that lead to bugs and wrong behaviours

### ISSUE THREAD

**Issue by maximelebreton** [kommitters/editorjs-toggle-block#189]
Hello, and first, thanks for your work!

### Description

When you copy / paste a toggle, the pasted block is created with the same foreign key (fk), so is not unique, and that's leading to wrong behaviours, like wrong child **items count**, and toggling both of the blocks when you click on one of them.

### Environment

* Plugin version : `"editorjs-toggle-block": "^0.3.5"`
* Editor.js version: `2.23.2`
* Plugins you use with their versions: ```"@editorjs/checklist": "1.3.0", "@editorjs/code": "2.7.0", "@editorjs/delimiter": "1.2.0", "@editorjs/editorjs": "2.23.2", "@editorjs/embed": "^2.5.3", "@editorjs/header": "2.6.2", "@editorjs/image": "2.6.2", "@editorjs/inline-code": "1.3.1", "@editorjs/link": "2.5.0", "@editorjs/link-autocomplete": "^0.0.0", "@editorjs/list": "1.6.2", "@editorjs/marker": "1.2.2", "@editorjs/paragraph": "2.8.0", "@editorjs/quote": "2.4.0", "@editorjs/raw": "2.3.0", "@editorjs/table": "2.0.1", "@editorjs/warning": "1.2.0",```
* Device, Browser, OS: Chrome Windows

### Current behavior

As you can see, copy/pasted toggle blocks dont have unique foreign keys: 
(so when I click on the first toggle, it open both of the toggles...)
![image](https://user-images.githubusercontent.com/1072425/221945415-a932b0d5-214c-4aab-900e-4baf0df61ecd.png)
![image](https://user-images.githubusercontent.com/1072425/221945435-daabf096-d496-458f-a4dd-b5bab90929cd.png)

But the biggest problem is for the items count, it seems to sum all the fk items, but as they are not unique, the count is wrong.

So here for example I have two toggles with one block inside (a paragraph), so the `items` count should be `1`.
But because the toggles share the samed fk, the `items` count is `2`... 

![image](https://user-images.githubusercontent.com/1072425/221952817-82ed7c7a-c9a7-42b1-87c4-3acf0f5a2ab0.png)

### Expected behavior

Any toggle block should have a **unique** foreign key

### Additional context

Used in Strapi admin with https://github.com/melishev/strapi-plugin-react-editorjs

Thanks for your time!

**Comment by miguelnietoa** [comment]
Hi @maximelebreton, thanks for submitting this issue! 
We'll review and notify you as soon as it is resolved.

**Comment by miguelnietoa** [comment]
Hi there, @maximelebreton 👋🏻 The bug was fixed in the version `0.3.10`, thanks for reporting!

Thank you @juliansg022 for addressing this issue 👏🏻
