### ISSUE TITLE
dropping block into toggle drops it into correct place but not part of toggle

### ISSUE THREAD

**Issue by gpeach** [kommitters/editorjs-toggle-block#203]
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Description

dropping block into toggle drops it into correct place but not part of toggle - the indent is different than toggle items plus closing toggle does not hide item

### Environment

* Editor.js version: latest
* Device, Browser, OS: windows local browser test

plugins:
<script src="https://cdn.jsdelivr.net/npm/@editorjs/editorjs@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-drag-drop"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-undo"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/image@2.3.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/header@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/paragraph@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/simple-image@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/embed@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/@editorjs/delimiter@latest"></script>
    <script src="https://cdn.jsdelivr.net/npm/editorjs-toggle-block"></script>

### Current behavior

to reproduce:
add a toggle block, click and add several text items
using shift tab, add another text item below the block
drag the outside block into the toggle
observe indent
try to close toggle

dragging items out works ok

### Expected behavior

I expect when dragging an item into the toggle block that it will match the indent and close with the toggle

**Comment by darksnake747** [comment]
I don't seem to be able to get a block into the toggle at all. I can click the space to add one, and get 1 new block in the toggle; but I cannot get any thing else in the toggle. I added the drag and drop plugin as well to see if I could drag one in, and that didn't work. If I press tab on an existing block, I get an error in the console and/or I see the tune menu open - but ultimately, it doesn't add the block to the toggle content either.

**Comment by MarioRodriguezS** [comment]
@gpeach @darksnake747 Thanks a lot for reporting the issue, it was solved and it is now available in `v0.3.13`.

Please let us know if this solution proves helpful to you.
