### ISSUE TITLE
Loading saved data does not work as excepted (block outside Toggle)

### ISSUE THREAD

**Issue by DblK** [kommitters/editorjs-toggle-block#206]
### Description

When you have multiple toggle, the editor does not load the data the right way.

### Environment

* Editor.js version: `2.27.2`
* Plugins you use with their versions:
* Device, Browser, OS: Mac, Chrome 114.0.5735.248, Ventura 13.4.1

### Current behavior

- Add a Toggle
- Add 2 blocks inside
- Add another Toggle
- Add 2 block inside
- Save
```json
{
    "time": 1691511752564,
    "blocks": [
        {
            "id": "VWsol6NDBR",
            "type": "toggle",
            "data": {
                "text": "Toggle 1",
                "status": "open",
                "fk": "fk-b433d56a-1d57-46df-bf84-1f7e2f774479",
                "items": 2
            }
        },
        {
            "id": "KQGdTvdEV4",
            "type": "paragraph",
            "data": {
                "text": "Block 1"
            }
        },
        {
            "id": "qENBUDHThb",
            "type": "paragraph",
            "data": {
                "text": "Block 2"
            }
        },
        {
            "id": "wqHgf_oq27",
            "type": "toggle",
            "data": {
                "text": "Toggle 2",
                "status": "open",
                "fk": "fk-63c007c2-9f03-4692-99d4-caf099ed44bb",
                "items": 2
            }
        },
        {
            "id": "lSciUXyKJE",
            "type": "paragraph",
            "data": {
                "text": "Block A"
            }
        },
        {
            "id": "EubqDL7fRK",
            "type": "paragraph",
            "data": {
                "text": "Block B"
            }
        }
    ],
    "version": "2.27.2"
}
```
- Load the editor with saved data

Block inside toggle are not anymore

![Screenshot 2023-08-08 at 18 22 53](https://github.com/kommitters/editorjs-toggle-block/assets/832617/fe39dd48-9696-4007-8e91-fcfaf79b734d)

### Expected behavior

The data should be saved and loaded to keep the same display.

![Screenshot 2023-08-08 at 18 22 35](https://github.com/kommitters/editorjs-toggle-block/assets/832617/418a7ab2-39c3-4d0a-a55f-2f08efd6acb7)

### Additional context

Works fine with one toggle but not with two...

**Comment by miguelnietoa** [comment]
We just released [v0.3.12](https://github.com/kommitters/editorjs-toggle-block/releases/tag/v0.3.12) which includes the fix for this issue.

Thank you @DblK for contributing ❤️
