### ISSUE TITLE
Adding blocks to Toggle only works for first Toggle

### ISSUE THREAD

**Issue by MrDigii** [kommitters/editorjs-toggle-block#223]
### Description

If I add a Toggle block I can add multiple following blocks to the toggle as desired. If I add another Toggle block I only can add on block to it. All others are not recognized as a part of the Toggle block.

### Environment

* Editor.js version: 2.28.0
* Plugins you use with their versions:
     -   @editorjs/nested-list: 1.3.0
     -   @editorjs/header: 2.7.0

* Device, Browser, OS: MacBook Pro M2, Chrome, Mac OS

### Current behavior

If I add a Toggle block I can add multiple following blocks to the toggle as desired. If I add another Toggle block I only can add on block to it. All others are not recognized as a part of the Toggle block.

### Expected behavior

No matter how many toggles are used, blocks can always be assigned to them.

### Additional context

editorjs-toggle-block version 0.3.14

**Comment by MarioRodriguezS** [comment]
@MrDigii Thanks a lot for reporting the issue. We have been trying to reproduce the issue but with no success, Could you please provide more context or share a code sandbox with the error?

When I try to add several toggle blocks with the given dependencies versions:

![Screenshot 2023-10-27 at 11 12 46 AM](https://github.com/kommitters/editorjs-toggle-block/assets/64106728/94b5af82-b3c8-4bff-bb88-4852651869b9)

**Comment by MrDigii** [comment]
@MarioRodriguezS Thank you for your fast response and effort.

I made a simple CodeSandbox to demonstrate the setup:
[CodeSandbox](https://codesandbox.io/embed/festive-khayyam-j443r9?fontsize=14&hidenavigation=1&theme=dark)

To show the problem I also made a GIF:
![editorjs-bug](https://github.com/kommitters/editorjs-toggle-block/assets/20514424/de75c4fa-3b68-4d8a-83a8-31455b6ee17d)

Thank for your help :)

**Comment by balex25** [comment]
You have to press the '**Tabs**' button on blocks that want to move inside a toggle container.

**Comment by MrDigii** [comment]
> You have to press the '**Tab**' button on blocks that want to move inside a toggle container.

I my tests the '**Tab**'  button functionality is not reliable. Sometimes the block automatically belongs to the toggle sometimes not. Also the different block types can interfere because they also use the same keybinding to display their own settings. 

So it's not very intuitive to use in my opinion. But maybe I missed something?

**Comment by miguelnietoa** [comment]
@MrDigii, thank you for reporting this. As you showed, currently, the toggle block plugin encounters limitations in handling List support effectively. We'll keep you informed of any developments on this matter.

**Comment by miguelnietoa** [comment]
@MrDigii @balex25, we're excited to announce the release of version [0.3.16](https://github.com/kommitters/editorjs-toggle-block/releases/tag/v0.3.16), addressing the reported issue. Kindly review it and confirm that the fix resolves the issue for you. Thanks!

**Comment by MrDigii** [comment]
> @MrDigii @balex25, we're excited to announce the release of version [0.3.16](https://github.com/kommitters/editorjs-toggle-block/releases/tag/v0.3.16), addressing the reported issue. Kindly review it and confirm that the fix resolves the issue for you. Thanks!

I tested it in my application and it looks good now. Thanks for your effort @miguelnietoa and team :)
