### ISSUE TITLE
Nested item auto-injected in latest toggle

### ISSUE THREAD

**Issue by balex25** [kommitters/editorjs-toggle-block#226]
### Description

When closing a nested toggle and writing a new block, and open/close the above nested toggle. Newly created block is auto-added to the open/close toggle.

### Current behavior

![chrome_0SDfO1WXj7](https://github.com/kommitters/editorjs-toggle-block/assets/37195461/bd76c106-b492-47b6-a45e-45c8dcb7180a)

### Expected behavior

Testing block should stay outside of the open/closed toggle, and not be auto-injected to the toggle. Only if the user presses the Tab key and the toggle is open should be injected into the toggle.

**Comment by miguelnietoa** [comment]
@balex25 We will take this into account when implementing the nested toggles feature.
See #170.

Feel free to contribute to the discussion on the linked issue if you have any additional insights
