### ISSUE TITLE
Wrong added toggle-block__item class, foreignkey, and id attributes on toggle deletion

### ISSUE THREAD

**Issue by balex25** [kommitters/editorjs-toggle-block#227]
### Description

When you delete a toggle it auto-added toggle-block__item class, foreignkey, and id attributes on the first above blocks, even if that block is not part of the deleted toggle.

### Current behavior

![chrome_0nzxBCb3RF](https://github.com/kommitters/editorjs-toggle-block/assets/37195461/feba68d8-c622-470b-98d0-83c6a4e89860)

### Expected behavior

No changes should be made to the previous block above of deleted toggle.

**Comment by muhammed-demir** [comment]
This bug still exists :(

**Comment by MarioRodriguezS** [comment]
@muhammed-demir We will be working on it soon, thanks for reporting!

**Comment by muhammed8figures** [comment]
> @muhammed-demir We will be working on it soon, thanks for reporting!

Approximately when might this error be fixed?

**Comment by MarioRodriguezS** [comment]
@muhammed-demir @balex25 @muhammed8figures Thanks a lot for reporting the issue, it was solved and the solution is available in editorjs-toggle-block v0.3.15. Please let us know if the solution is helpful for you. Cheers!
