### ISSUE TITLE
Wrong deletion with nested toggle items

### ISSUE THREAD

**Issue by balex25** [kommitters/editorjs-toggle-block#228]
### Description

When you remove a nested toggle, some child items are not deleted.

### Current behavior

![chrome_iFgacjxPXm](https://github.com/kommitters/editorjs-toggle-block/assets/37195461/a35d090c-0007-4f91-a54a-13600c6cfb89)

### Expected behavior

To remove all children of the nested toggle.

**Comment by miguelnietoa** [comment]
@balex25 We will take this into account when implementing the nested toggles feature. 👍🏻 
See #170.

Feel free to contribute to the discussion on the linked issue if you have any additional insights.
