### ISSUE TITLE
Extend the plugin support

### ISSUE THREAD

**Issue by juliansg022** [kommitters/editorjs-toggle-block#48]
ℹ️ This issue is an Epic

## Context
`editorjs-toggle-block` is a plugin implemented to be used in [Editor.js](https://github.com/codex-team/editor.js). The plugin was developed according to the [Editor.js guides](https://editorjs.io).

## Objective
It's required to extend the functionality of the plugin so that more block types are supported within a toggle, and also to be compatible with the [EditorJS Drag/Drop Plugin](https://github.com/kommitters/editorjs-drag-drop)

## Checklist

- [x] #57 
- [x] #50 
- [x] #49 
- [x] #51
- [x] #32

**Comment by santiagoboterokommit** [comment]
@juliansg022 All items in the checklist are done
