### ISSUE TITLE
Bug for undo and redo actions

### ISSUE THREAD

**Issue by santiagoboterokommit** [kommitters/editorjs-toggle-block#70]
### Precheck

- [ ] Do a quick search and make sure the bug has not been reported yet.
- [ ] Please disclose security vulnerabilities privately at [oss@kommit.co](mailto:oss@kommit.co).
- [ ] Finally, be nice and have fun!.

### Description

Relative to #57 
When a drag and drop action is done, if we undo the action (ctrl+z) the page gets freeze

### Environment

* Editor.js version: 2.24.3
* Plugins you use with their versions: 
                     * [editor.js undo](https://github.com/kommitters/editorjs-undo) - v0.2.1
                     * [editorjs toggle block](https://github.com/kommitters/editorjs-toggle-block) - v0.1.2
* Device, Browser, OS: [brave](https://brave.com/)

### Current behaviour

When we drag and drop a toggle block, and try to undo that action, the page gets freeze

### Expected behaviour

A proper implementation from undo and redo actions where we can undo drag and drop actions

### Additional context

It is happening with children too

**Comment by santiagoboterokommit** [comment]
This happens when we have initial data. in the docs of Undo plugin, we can find a code when we have initial data
```
        const undo = new Undo({ editor });
        undo.initialize(initialData);
```
There is no freeze on the page when we make undo actions. but Undo is not supported to drag-N-drop actions yet

**Comment by MarthoxGT** [comment]
This issue should be solved by updating the undo plugin to the latest version (v2.0.3)[https://github.com/kommitters/editorjs-undo/releases/tag/v2.0.3]
